version: "3.9"
services:
  cron:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LOG_LEVEL: info
    deploy:
      placement:
        constraints: [ node.role == manager ]

  gateway:
    image: ${REGISTRY}/lk-social-gateway:${IMAGE_TAG}
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
      - target: 8081
        published: 8888
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - app_net

  client:
    image: ${REGISTRY}/lk-social-client:${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - app_net

  api:
    image: ${REGISTRY}/lk-social-api:${IMAGE_TAG}
    volumes:
      - uploads:/app/storage/app/public
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - app_net

  api-php-fpm:
    image: ${REGISTRY}/lk-social-api-php-fpm:${IMAGE_TAG}
    environment:
      APP_NAME: Личный кабинет 120на80
      APP_URL: http://192.168.2.19:8888
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_HOST: api-db
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: secret
      FILESYSTEM_DISK: public
      SANCTUM_STATEFUL_DOMAINS: 192.168.2.19:8888
      # FILESYSTEM_DISK: sftp
      # SFTP_URL: http://192.168.2.3/static/s
      # SFTP_HOST: 192.168.2.3
      # SFTP_USERNAME: Social
      # SFTP_PASSWORD: 222326
      PUSHER_APP_ID: 1624213
      PUSHER_APP_KEY: e40e9c78f88612ad8a35
      PUSHER_APP_SECRET: 5eea170da1dad7380c42
    volumes:
      - uploads:/app/storage/app/public
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - app_net

  api-migration:
    image: ${REGISTRY}/lk-social-api-php-cli:${IMAGE_TAG}
    environment:
      DB_HOST: api-db
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: secret
    command: sh -c 'wait-for-it api-db:3306 -t 60 && php artisan migrate --force'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    networks:
      - app_net

  api-db:
    image: mariadb:10.8
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: app
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: [ node.role == manager ]
      endpoint_mode: dnsrr
    networks:
      - app_net

  scheduler:
    image: ${REGISTRY}/lk-social-api-php-cli:${IMAGE_TAG}
    environment:
      APP_NAME: Личный кабинет 120на80
      APP_URL: http://192.168.2.19:8888
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_HOST: api-db
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: secret
      FILESYSTEM_DISK: public
      # FILESYSTEM_DISK: sftp
      # SFTP_URL: http://192.168.2.3/static/s
      # SFTP_HOST: 192.168.2.3
      # SFTP_USERNAME: Social
      # SFTP_PASSWORD: 222326
    volumes:
      - uploads:/app/storage/app/public
    command: sh -c 'php artisan schedule:run'
    deploy:
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=* * * * *
        - swarm.cronjob.skip-running=true
      replicas: 0
      restart_policy:
        condition: none

volumes:
  db-data:
  uploads:


networks:
  app_net:
    name: app_net
    ipam:
      driver: default
      config:
        - subnet: 192.168.199.0/24
