version: "3.9"
services:
  gateway:
    image: ${REGISTRY}/lk-social-gateway:${IMAGE_TAG}
    ports:
      - "80:8080"
      - "8888:8081"

  client:
    image: ${REGISTRY}/lk-social-client:${IMAGE_TAG}

  api:
    image: ${REGISTRY}/lk-social-api:${IMAGE_TAG}
    volumes:
      - uploads:/app/storage/app/public

  api-php-fpm:
    image: ${REGISTRY}/lk-social-api-php-fpm:${IMAGE_TAG}
    environment:
      APP_NAME: Личный кабинет 120на80
      APP_URL: http://localhost:8888
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_HOST: api-db
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: secret
      FILESYSTEM_DISK: sftp
      SFTP_URL: http://192.168.2.3/static/s
      SFTP_HOST: 192.168.2.3
      SFTP_USERNAME: Social
      SFTP_PASSWORD: 222326
    volumes:
      - uploads:/app/storage/app/public

  api-migration:
    image: ${REGISTRY}/lk-social-api-php-cli:${IMAGE_TAG}
    environment:
      DB_HOST: api-db
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: secret
    command: sh -c 'wait-for-it api-db:3306 -t 60 && php artisan migrate --force'

  api-db:
    image: mariadb:10.8
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: app
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
  uploads:
